#ifndef __SGI_STL_INTERNAL_UNINITIALIZED_H
#define __SGI_STL_INTERNAL_UNINITIALIZED_H

#include "stl_config.h"

__STL_BEGIN_NAMESPACE




__STL_END_NAMESPACE

#endif /*__SGI_STL_INTERNAL_UNINITIALIZED_H*/